#!/bin/bash
# https://ericmjl.github.io/blog/2021/7/10/how-to-enable-custom-source-package-installation-in-binder/
set -e  # don't allow errors to fail silently
which pip  # in case the wrong `pip` is used, this will let us debug
pip install -e .  # install the custom library
python3 -m spacy download de_core_news_sm
