# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"get_file_paths": "00_html_parsing.ipynb",
         "RE_HTM": "00_html_parsing.ipynb",
         "collect_sheet_uris": "00_html_parsing.ipynb",
         "RE_SHEET": "00_html_parsing.ipynb",
         "download_sheet": "00_html_parsing.ipynb",
         "download_multiple_sheets": "00_html_parsing.ipynb",
         "RE_FNAME": "00_html_parsing.ipynb",
         "is_date": "00_html_parsing.ipynb",
         "get_sheet_df": "00_html_parsing.ipynb",
         "handle_title_and_date": "00_html_parsing.ipynb",
         "disambiguate_party": "00_html_parsing.ipynb",
         "VOTE_COLS": "00_html_parsing.ipynb",
         "PARTY_MAP": "00_html_parsing.ipynb",
         "get_squished_dataframe": "00_html_parsing.ipynb",
         "set_sheet_dtypes": "00_html_parsing.ipynb",
         "DTYPES": "00_html_parsing.ipynb",
         "get_multiple_sheets_df": "00_html_parsing.ipynb",
         "get_multiple_sheets": "00_html_parsing.ipynb",
         "pd.options.plotting.backend": "04_vote_prediction.ipynb",
         "get_votes_by_party": "01_similarities.ipynb",
         "prepare_votes_of_mdb": "01_similarities.ipynb",
         "align_mdb_with_parties": "01_similarities.ipynb",
         "compute_similarity": "01_similarities.ipynb",
         "get_mdb_party_similarity": "01_similarities.ipynb",
         "plot_similarity_over_time": "01_similarities.ipynb",
         "align_party_with_party": "01_similarities.ipynb",
         "align_party_with_all_parties": "01_similarities.ipynb",
         "get_party_party_similarity": "01_similarities.ipynb",
         "GUI": "04_vote_prediction.ipynb",
         "ABGEORDNETENWATCH_PATH": "03_abgeordnetenwatch_data.ipynb",
         "API_ENCODING": "03_abgeordnetenwatch_data.ipynb",
         "get_poll_info": "03_abgeordnetenwatch_data.ipynb",
         "store_polls_json": "03_abgeordnetenwatch_data.ipynb",
         "load_polls_json": "03_abgeordnetenwatch_data.ipynb",
         "parse_poll_data": "03_abgeordnetenwatch_data.ipynb",
         "test_poll_data": "03_abgeordnetenwatch_data.ipynb",
         "get_polls_df": "03_abgeordnetenwatch_data.ipynb",
         "get_mandates_info": "03_abgeordnetenwatch_data.ipynb",
         "store_mandates_info": "03_abgeordnetenwatch_data.ipynb",
         "load_mandate_json": "03_abgeordnetenwatch_data.ipynb",
         "parse_mandate_data": "03_abgeordnetenwatch_data.ipynb",
         "test_mandate_data": "03_abgeordnetenwatch_data.ipynb",
         "get_mandates_df": "03_abgeordnetenwatch_data.ipynb",
         "get_vote_info": "03_abgeordnetenwatch_data.ipynb",
         "store_vote_info": "03_abgeordnetenwatch_data.ipynb",
         "check_stored_vote_ids": "03_abgeordnetenwatch_data.ipynb",
         "load_vote_json": "03_abgeordnetenwatch_data.ipynb",
         "parse_vote_data": "03_abgeordnetenwatch_data.ipynb",
         "test_vote_data": "03_abgeordnetenwatch_data.ipynb",
         "get_votes_df": "03_abgeordnetenwatch_data.ipynb",
         "get_all_remaining_vote_info": "03_abgeordnetenwatch_data.ipynb",
         "compile_votes_data": "03_abgeordnetenwatch_data.ipynb"}

modules = ["parsing.py",
           "similarity.py",
           "gui.py",
           "abgeordnetenwatch.py",
           "ml.py"]

doc_url = "https://eschmidt42.github.io/bundestag/"

git_url = "https://github.com/eschmidt42/bundestag/tree/master/"

def custom_doc_links(name): return None
