# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"get_file_paths": "00_html_parsing.ipynb",
         "RE_HTM": "00_html_parsing.ipynb",
         "collect_sheet_uris": "00_html_parsing.ipynb",
         "RE_SHEET": "00_html_parsing.ipynb",
         "download_sheet": "00_html_parsing.ipynb",
         "download_multiple_sheets": "00_html_parsing.ipynb",
         "RE_FNAME": "00_html_parsing.ipynb",
         "is_date": "00_html_parsing.ipynb",
         "get_sheet_df": "00_html_parsing.ipynb",
         "handle_title_and_date": "00_html_parsing.ipynb",
         "disambiguate_party": "00_html_parsing.ipynb",
         "VOTE_COLS": "02_member_similarity.ipynb",
         "PARTY_MAP": "00_html_parsing.ipynb",
         "get_squished_dataframe": "02_member_similarity.ipynb",
         "set_sheet_dtypes": "00_html_parsing.ipynb",
         "DTYPES": "00_html_parsing.ipynb",
         "get_multiple_sheets_df": "00_html_parsing.ipynb",
         "get_multiple_sheets": "00_html_parsing.ipynb",
         "get_agreements_painfully_slow": "02_member_similarity.ipynb",
         "get_dummy": "02_member_similarity.ipynb",
         "scan_all_agreements": "02_member_similarity.ipynb",
         "path": "03_gui.ipynb",
         "df": "03_gui.ipynb",
         "GUI": "03_gui.ipynb"}

modules = ["parsing.py",
           "similarity.py",
           "gui.py"]

doc_url = "https://eschmidt42.github.io/bundestag/"

git_url = "https://github.com/eschmidt42/bundestag/tree/master/"

def custom_doc_links(name): return None
