name: documentation

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-24.04
    timeout-minutes: 10

    strategy:
      matrix:
        python-version:
          - "3.12"

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        version: "0.7.4"
        enable-cache: true
        cache-dependency-glob: "uv.lock"

    - name: Set up Python ${{ matrix.python-version }}
      run: uv python install ${{ matrix.python-version }}

    - name: Create virtal environment
      run: |-
          make install-docs-env

    - name: Download data
      run: |-
          uv run bundestag download huggingface --y

    - name: Build documentation
      run: |-
          make docs

    - name: Deploy documentation
      run: |-
          uv run mkdocs gh-deploy --force
