# Deploy MkDocs site via Upload/Deploy Pages actions (recommended)
permissions:
  contents: write
  pages: write
  id-token: write

name: documentation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    strategy:
      matrix:
        python-version:
          - "3.12"

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        version: "0.7.4"
        enable-cache: true
        cache-dependency-glob: "uv.lock"

    - name: Set up Python ${{ matrix.python-version }}
      run: uv python install ${{ matrix.python-version }}

    - name: Create virtual environment
      run: make install-docs-env

    - name: Download data
      run: uv run bundestag download huggingface --y

    - name: Build documentation (mkdocs)
      # Ensure this produces the static site in the 'site' directory
      run: |
        uv run mkdocs build -d site

    - name: Upload Pages artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: site

    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v4
