name: documentation
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Setup python
      uses: actions/setup-python@v4
      with:
          python-version: '3.9.16'

    - name: Create virtal environment
      run: |-
          make venv
          make install-docs

    - name: Build documentation
      run: |-
          make docs

    - name: Deploy documentation
      run: |-
          source .venv/bin/activate
          mkdocs gh-deploy --force
