name: documentation
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:

        - name: Checkout repo
          uses: actions/checkout@v3

        - name: Set up Python
          uses: actions/setup-python@v4
          with:
            python-version: '3.9.16'

        - name: Create virtal environment
          run: |-
              make venv
              make install-dev

        - name: Build documentation
          run: |-
              make docs

        - name: Deploy documentation
          run: |-
              source .venv/bin/activate
              mkdocs gh-deploy --force
