# This job sets up poetry and runs unittests on every push
name: Tests

on:
  push

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
            - name: Check out repository
              uses: actions/checkout@v2

            - name: Setup python
              uses: actions/setup-python@v2
              with:
                  python-version: '3.9.16'
        
            - name: Create virtal environment
              run: |-
                  python3 -m venv .venv
            - name: Install dependencies
              run: |-
                  source .venv/bin/activate
                  python -m pip install --upgrade pip
                  pip install pip-tools==6.12.3
                  pip-sync requirements/dev-requirements.txt
            # - name: Run tests
            #   run: |-
            #       source .venv/bin/activate
            #       coverage run -m pytest -v src/tests/
            #       coverage report --omit="src/tests/*"
